# Generated by Django 6.0.6 on 2026-06-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lieux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='buvettes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lieu',
            name='toilettes',
            field=models.BooleanField(default=False),
        ),
    ]
