# Generated by Django 5.2 on 2025-04-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='categorie',
            new_name='categorie_id',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='lieu',
            new_name='lieu_id',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='organisateur',
            new_name='organisateur_id',
        ),
    ]
